NEONScience/NEON-IS-data-processing

- pack/NEONprocIS.base/R/def.loc.filt.R
- pack/NEONprocIS.base/tests/testthat/locations-invalid.json
- pack/NEONprocIS.base/tests/testthat/locations.json
- pack/NEONprocIS.base/tests/testthat/test-loc-filt-functions.R
- Note that the branch name is choim_NSE6057_V3.  
- This is a revised branch of choim_NSE6057 after the code formatting applied to the master as agreed.
- Has reviews from Cove implemented.
> Choim nse6057 v3

- pack/NEONprocIS.base/R/def.validate.list.R
- pack/NEONprocIS.cal/R/def.cal.conv.poly.R
- pack/NEONprocIS.cal/tests/testthat/test-cal-functions.R
@covesturtevant 
Hi Cove, 
Let me know when you have time. I can do a demo for you.
> Choim nse6229 final

- pack/NEONprocIS.base/R/def.validate.xml.schema.R
- pack/NEONprocIS.cal/R/def.read.cal.xml.R
- pack/NEONprocIS.cal/tests/testthat/calibration-timeMissing.xml
- pack/NEONprocIS.cal/tests/testthat/calibration.xml
- pack/NEONprocIS.cal/tests/testthat/calibration.xsd
- pack/NEONprocIS.cal/tests/testthat/test-read-cal-xml.R
Hi @covesturtevant ,
I can do a quick demo when you have time. Thanks
> read.cal.xml unit test final

- pack/NEONprocIS.base/data/calibration.xsd
- pack/NEONprocIS.base/data/locations-schema.json
- pack/NEONprocIS.cal/tests/testthat/test-cal-func-poly.R
This PR has one file, test-cal-func-poly.R, added. It is the unit test for def.ca.func.poly.R after the change you made in def.validate.cal.info.R.
- The test has 3 scenarios, 1 positive when the input params are valid, 2 negatives. 
--- One of the negative is input param list is valid, but does not have the expected name, cal.
--- The other is, a data frame is passed on. 
FYI:  PR# 16 is closed.  I will rework, clean the code and create a new one later.
> add unit test for def.cal.func.poly.R

- pack/NEONprocIS.cal/tests/testthat/test-ucrt-wq-temp-conc.R
- pack/NEONprocIS.cal/tests/testthat/testdata/calibration22.xml
- pack/NEONprocIS.cal/tests/testthat/testdata/calibration222.xml
Hi @kcawley, 
This is the unit test of def.ucrt.wq.temp.conc.R.  I can do a quick demo tomorrow.
> adding unit test for def.ucrt.wq.temp.conc.R

- pipe/pressureAir/pressureAir_qaqc_plausibility.json
- pipe/pressureAir/pressureAir_quality_metrics.json
- pipe/pressureAir/pressureAir_related_location_group.json
- pipe/pressureAir/pressureAir_statistics.json
- pipe/ptb330a/ptb330a_date_gap_filler.json
- pipe/ptb330a/ptb330a_date_gap_filler_limiter.yaml
> Choim pressure air latest

- modules/date_gap_filler/data_file_linker.py
- modules/date_gap_filler/date_gap_filler_config.py
- modules/date_gap_filler/date_gap_filler_main.py
- modules/date_gap_filler/empty_files.py
- modules/date_gap_filler/location_file_linker.py
- modules/date_gap_filler_linker/date_gap_filler_linker.py
- modules/date_gap_filler_linker/date_gap_filler_linker_main.py
- pipe/prt/prt_calibrated_location_group.yaml
- pipe/prt/prt_date_gap_filler.yaml
- pipe/prt/prt_date_gap_filler_linker.yaml
Add option to copy vs. symlink in date_gap_filler module.
> add option to copy vs. symlink in date_gap_filler modules

- modules/data_access/get_assets.py
- modules/location_asset_loader/location_asset_loader.py
- modules/location_asset_loader/location_asset_loader_main.py
- pipe/csat3/location_asset_csat3.yaml
- pipe/dualfan/location_asset_dualfan.yaml
- pipe/li191r/location_asset_li191r.yaml
- pipe/li7200/location_asset_li7200.yaml
- pipe/mti300ahrs/location_asset_mti300ahrs.yaml
- pipe/pqs1/location_asset_pqs1.yaml
- pipe/prt/location_asset_prt.yaml
- pipe/ptb330a/location_asset_ptb330a.yaml
- pipe/tchain/location_asset_tchain.yaml
- pipe/windobserverii/location_asset_windobserverii.yaml
Hi @covesturtevant , 
This PR is for you to review sensor-specific location_asset repos.
> Choim nse8066

- modules/data_access/get_named_locations.py
- modules/location_loader/location_loader.py
- modules/location_loader/location_loader_main.py
- pipe/csat3/location_loader_csat3.yaml
- pipe/li191r/location_loader_li191r.yaml
- pipe/li7200/location_loader_li7200.yaml
- pipe/mti300ahrs/location_loader_mti300ahrs.yaml
- pipe/pqs1/location_loader_pqs1.yaml
- pipe/prt/location_loader_prt.yaml
- pipe/ptb330a/location_loader_ptb330a.yaml
- pipe/tchain/location_loader_tchain.yaml
Hi @covesturtevant, 
This is for you to review the location_loader per sensor type.
Thanks,
> Choim nse8724 v4

- modules/data_access/get_thresholds.py
- modules/threshold_loader/threshold_loader.py
- modules/threshold_loader/threshold_loader_main.py
- pipe/parWaterSurface/threshold_loader_parWaterSurface.yaml
- pipe/pressureAir/threshold_loader_pressureAir.yaml
- pipe/tempAirSingle/threshold_loader_tempAirSingle.yaml
Hi @covesturtevant, 
This is PR for threshold split story.   Thanks
> Choim nse8800 threshold

- pipe/prt/prt_date_gap_filler.yaml
- pipe/tempSoil/tempSoil_level1_location_group.yaml
- pipe/tempSoil/tempSoil_level1_package.yaml
- pipe/tempSoil/tempSoil_level1_transform.yaml
migrate pub pipelines to pachy 2.x and test
> update and test pub pipeline specs

- modules/data_access/get_group_loaders.py
- modules/group_loader/group_loader.py
- pipe/test-group/group_loader_test-gcp.yaml
The code is updated for any GROUP_PREFIX. Thanks
> allow less restricted input GROUP_PREFIX

- modules/data_access/get_named_locations.py
- modules/data_access/types/geojson_converter.py
- modules/data_access/types/named_location.py
- pipe/aquatroll200/location_loader_aquatroll200.yaml
- pipe/csat3/location_loader_csat3.yaml
- pipe/hmp155/hmp155_location_loader.yaml
- pipe/leveltroll500/location_loader_leveltroll500.yaml
- pipe/li191r/location_loader_li191r.yaml
- pipe/li7200/location_loader_li7200.yaml
- pipe/mcseries/location_loader_mcseries.yaml
- pipe/mti300ahrs/location_loader_mti300ahrs.yaml
- pipe/pqs1/location_loader_pqs1.yaml
- pipe/pressuretransducer/pressuretransducer_location_loader.yaml
- pipe/prt/location_loader_prt.yaml
- pipe/ptb330a/ptb330a_location_loader.yaml
- pipe/tchain/location_loader_tchain.yaml
Group is removed in the location_loader.  The build is 122.
> Choim nse9333

- pack/NEONprocIS.base/DESCRIPTION
- pack/NEONprocIS.base/R/def.loc.meta.R
- pack/NEONprocIS.base/inst/extdata/locations-namedLocation-schema.json
- pack/NEONprocIS.base/inst/extdata/locations-sensor-schema.json
- pack/NEONprocIS.base/tests/testthat/def.loc.meta/test_input/pfs/2019/01/02/CFGLOC101580/location/prt_20208_locations.json
- pack/NEONprocIS.base/tests/testthat/def.loc.meta/test_input/pfs/2019/01/02/CFGLOC101580/location/prt_20208_locations_alldates_null.json
- pack/NEONprocIS.base/tests/testthat/def.loc.meta/test_input/pfs/2020/12/31/CFGLOC113261/location/CFGLOC113261.json
- pack/NEONprocIS.base/tests/testthat/def.loc.meta/test_input/pfs/2020/12/31/CFGLOC113261/location/CFGLOC113261_2.json
- pack/NEONprocIS.base/tests/testthat/def.loc.meta/test_input/pfs/prt_calibrated_location_group/prt/2019/01/01/16247/prt_16247_location.json
def.loc.meta.R, location related schemas and the test location jsons are updated accordingly with the group removed from the location-loader json.
> Choim nse9351

- modules/data_access/get_asset_locations.py
- modules/data_access/types/asset_location.py
- modules/data_access/types/geojson_converter.py
- pipe/aquatroll200/location_asset_aquatroll200.yaml
- pipe/csat3/location_asset_csat3.yaml
- pipe/dualfan/location_asset_dualfan.yaml
- pipe/hmp155/hmp155_location_asset.yaml
- pipe/leveltroll500/location_asset_leveltroll500.yaml
- pipe/li191r/location_asset_li191r.yaml
- pipe/li7200/location_asset_li7200.yaml
- pipe/mcseries/location_asset_mcseries.yaml
- pipe/mti300ahrs/location_asset_mti300ahrs.yaml
- pipe/pqs1/location_asset_pqs1.yaml
- pipe/pressuretransducer/pressuretransducer_location_asset.yaml
- pipe/prt/location_asset_prt.yaml
- pipe/ptb330a/ptb330a_location_asset.yaml
- pipe/tchain/location_asset_tchain.yaml
- pipe/windobserverii/location_asset_windobserverii.yaml
This is location_asset_loader with group removed.
> Choim nse9334 v2

- modules/data_access/get_group_loaders.py
- modules/data_access/types/geojson_converter.py
- modules/data_access/types/group.py
- pipe/test-group/group_loader_test-gcp.yaml
- pipe/test-group/srf_loader_test.yaml
Hi @covesturtevant , 
data_product_ID is added to group.  The files are copied over in SOM, pfs/group_loader_test_B553/, fyi.
> data_product_ID is added to group

- modules/group_loader/tests/test_group_loader.py
test_group_loader fixed after the latest changes in group_loader
> test-group-loader fixed

- modules/data_access/tests/test_dp_pub_records.py
Unit test for get_dp_pub_records.py is added.
> add unit test for dp_pub_records function

- pack/NEONprocIS.base/tests/testthat/def.grp.meta/CFGLOC100245.json
- pack/NEONprocIS.base/tests/testthat/test-def.grp.meta.R
Update test json for def.grp.meta.R unit test to accommodate the group_loader change
> Choim nse9659

- pack/NEONprocIS.qaqc/tests/testthat/test-def.qm.dp0p.R
A negative test is added to test-def.qm.dp0p.R.
> a negative test is added

- modules/data_access/get_sync_pubs.py
- modules/pub_sync/pub_sync.py
- modules/pub_sync/pub_sync_main.py
- modules/pub_sync/tests/test_pub_sync.py
- pipe/parQuantumLine/mijatest_level1_pub_sync.yaml
- pipe/parQuantumLine/parQuantumLine_level1_pub_sync.yaml
This is for pub_sync refactoring.  Thanks
> Choim nse9710

- modules/pub_sync/pub_sync.py
- modules/pub_sync/tests/dp_pub_data.py
- modules/pub_sync/tests/test_pub_sync.py
Adding unit test and the test data for pub_sync.
> Choim nse9762

- modules/pub_workbook_loader/tests/test_pub_workbook_loader.py
Add unit test to pub_workbook_loader
> Pub workbook loader unittest

- modules/pub_egress/tests/test_pub_egress.py
unit test is updated. It runs successfully.
> Choim nse9733

- modules/pub_grouper/tests/test_pub_grouper.py
I added a small change to pub_grouper module unit test after pulling the latest pub_grouper module.
It is to ensure getting a cross-platform temp directory. I can do a demo if you need to see the difference.
> Choim nse9807 tempfile

- modules/calval_loader/load_all_calval_files.py
Adding err_datum to load_all_calval_files.py
> Choim nse9956

- modules/pub_transformer/pub_transformer.py
Adding err_datum to pub_transformer.py
> Choim nse9959

- modules/pub_transformer/pub_transformer.py
> Revert "Choim nse9959"

- modules/calval_loader/load_all_calval_files.py
Reverts NEONScience/NEON-IS-data-processing#210
> Revert "Choim nse9956"

- pipe/groundwaterPhysical/groundwaterPhysical_pub_egress_and_publish.yaml
- pipe/parQuantumLine/parQuantumLine_pub_egress_and_publish.yaml
- pipe/parWaterSurface/parWaterSurface_pub_egress_and_publish.yaml
- pipe/relHumidity/relHumidity_pub_egress_and_publish.yaml
- pipe/surfacewaterPhysical/surfacewaterPhysical_pub_egress_and_publish.yaml
- pipe/tempSoil/tempSoil_pub_egress_and_publish.yaml
That was fast, I forgot to update the ERR_PATH in the yamls (I was using test yaml.)
> ERR_PATH updated in the yamls

- flow/flow.troll.cond.conv/wrap.troll.cond.conv.R
- pipe/aquatroll200/aquatroll200_flags_specific_and_cond_conv.yaml
mija found a typo through her unit testing
> minor update

- flow/flow.troll.cond.conv/wrap.troll.cond.conv.R
- flow/flow.troll.flags/wrap.troll.flags.R
- flow/flow.troll.logfiles/wrap.troll.logfiles.R
- flow/flow.troll.uncertainty/wrap.troll.uncertainty.R
- pipe/aquatroll200/aquatroll200_cond_conv.yaml
- pipe/aquatroll200/aquatroll200_flags_specific.yaml
- pipe/groundwaterPhysical/groundwaterPhysical_stats_ucrt_group_and_compute.yaml
- pipe/leveltroll500/leveltroll500_flags_specific.yaml
- pipe/surfacewaterPhysical/surfacewaterPhysical_stats_ucrt_grp_comp.yaml
> image update

- flow/flow.troll.logfiles.fill/build_tag_push_update.sh
- flow/flow.troll.logfiles.fill/flow.troll.logfiles.fill.R
- flow/flow.troll.logfiles.fill/wrap.troll.logfiles.fill.R
- pipe/aquatroll200/aquatroll200_fill_log_files.yaml
- pipe/leveltroll500/leveltroll500_fill_log_files.yaml
> update for unit test

- pipe/metone370380/metone370380_calibration_assignment.yaml
- pipe/metone370380/metone370380_calibration_group_and_convert.yaml
- pipe/metone370380/metone370380_calibration_list_files.yaml
- pipe/metone370380/metone370380_calibration_loader.yaml
- pipe/metone370380/metone370380_data_source_trino.yaml
- pipe/metone370380/metone370380_fill_date_gaps_and_regularize.yaml
- pipe/metone370380/metone370380_location_active_dates_assignment.yaml
- pipe/metone370380/metone370380_location_asset.yaml
- pipe/metone370380/metone370380_location_asset_assignment.yaml
- pipe/metone370380/metone370380_location_group_and_restructure.yaml
- pipe/metone370380/metone370380_location_loader.yaml
Cove, Please review the pipelines that i created for metone370380 event
> adding pipeline specificationf for metone370380 event

- flow/tests/testthat/test-wrap-cal-conv-dp0p.R
Hi @covesturtevant, 
This is to fix the test failure in Jenkins. 
Thanks!
> add non-null value catch in the test

- flow/tests/testthat/test-wrap-troll-logfiles.R
@ncatolico  or @covesturtevant , 
This PR is the unit test update after the param change, from "DirIn" to "FileIn", in wrap.troll.logfiles.R. 
I am fine with either of you whoever has time to review. I am just letting you all know ( including @eahayes9 ) that the test is updated accordingly. Thanks!
> Choim nse10471 v3

- modules/processed_datums_reader/app.py
- modules/processed_datums_reader/main.py
- modules/processed_datums_reader/reader.py
- modules/processed_datums_reader/writer.py
- pipe/processed_datums_reader.yaml
Made changes to move the pipeline variable from python code to pipeline spec file
> Nse 10468 pachy dashboard

- .github/actions/build-and-push/action.yml
- .github/workflows/neon-is-group-loader.yml
Hi @covesturtevant and @eahayes9, 
This PR is to push multi tag image. Thanks.
> dir name is changed to build-and-push and multi tags added

- .github/actions/build-push-update/action.yml
@eahayes9 , 
- is removed from t arg.
> remove - from tag arg

- .github/actions/build-push-update/action.yml
@eahayes9 , 
The dependency set up is commented out as we discussed.
> comment out the dependency set up

- .github/actions/test-auth/action.yml
- .github/workflows/neon-test-auth.yml
Testing checking out a new branch with a Google Service Account
> Test auth with github and gcp

- .github/actions/build-push-update/action.yml
- .github/workflows/neon-is-location-loader.yml
- pipe/turbulent/turbulent_group_loader.yaml
This is a clean branch of choim-*V2-PR.
> clean branch

- modules/errored_datums_reader/writer.py
- modules/processed_datums_reader/reader.py
- modules/processed_datums_reader/writer.py
- pipe/errored_datums_reader/errored_datums_reader.yaml
- pipe/processed_datums_reader/processed_datums_reader.yaml
Please review the changes made to both Errored_datums_reader and Processed_datums_reader modules
> Nse 10515 GitHub actions

- .github/actions/put-files/action.yml
- .github/workflows/DEV_level1_pipeline_list.yml
- .github/workflows/DEV_li191r_site_list.yml
- .github/workflows/DEV_troll_site_list.yml
1. all the CERT wfs are reverted and one DEV workflows, DEV-level1-pipeline-list only worked/tested. 
2. I will update the other 2 when Dawn approves. 
@ddlenz , 
3. inputs defined in the action 
4. the env vars set in the action from the inputs, 
5. the env var values passed into the action from your workflow using "with"
> Choim nse10539 dev workflows

- .github/workflows/DEV_prt_site_list.yml
- .github/workflows/DEV_prt_tempSoil_update_dag.yml
- pipe/prt/site-list.json
- pipe/tempSoil/tempSoil_cron_monthly_and_pub_control.yaml
Cove, this branch is for "PRT" and "tempsoil" pipelines, please review the changes and let me know your comments
> Made changes to match the start date with the prt pipelines

- .github/actions/put-files/action.yml
@covesturtevant and @ddlenz, 
This is implementing the final piece of the feedback from PR# 313 about 2 weeks ago, 
"the action steps need to set corresponding env vars for the python script to use"
And tested.
> add env vars

- .github/workflows/DEV_prt_tempSurfacewater_update_dag.yml
- .github/workflows/DEV_windobserverii_site_list.yml
Cove, please review github actions for both tempSurfacewater and Windobserverii.
> add github actions for tempSurfacewater and windobserverii pipelines

- .github/workflows/DEV_windobserverii_update_dag.yml
Cove, added github actions for windobserverii, please review and let me know your comments.
> added github actions file for windobserverii update dag workflow

- .github/workflows/DEV_dualfan_site_list.yml
- .github/workflows/DEV_dualfan_update_dag.yml
Added github actions for dualfan
> added github actions for dualfan

- .github/actions/build-push-update/action.yml
- .github/actions/build-push/action.yml
- .github/actions/get-changed-files/action.yml
- .github/actions/update-pipelines/action.yml
- .github/workflows/DEV_errored_datums_reader.yml
- .github/workflows/DEV_processed_datums_reader.yml
- .github/workflows/build_push_errored_datums_reader.yml
- .github/workflows/build_push_update_errored_datums_reader.yml
- modules/group_loader/Dockerfile
- modules/group_loader/build_tag_push_update.sh
- modules/location_loader/Dockerfile
- modules/location_loader/build_tag_push_update.sh
- pipe/turbulent/turbulent_group_loader.yaml
Reverts NEONScience/NEON-IS-data-processing#345
> Revert "Revert "Choim nse10541 10682 v2""

- modules/timeseries_padder/tests/test_timeseries_padder.py
- modules/timeseries_padder/timeseries_padder/timeseries_padder_config.py
Hi @eahayes9, 
The unit test for timeseries_padder is fixed. Requesting review. Thanks.
> Choim timeseries padder unittest fix

- .github/workflows/build_push_stats_group_and_compute.yml
- .github/workflows/build_push_update_stats_group_and_compute.yml
- modules_combined/stats_group_and_compute/Dockerfile
- modules_combined/stats_group_and_compute/build_tag_push_update.sh
- pipe/parQuantumLine/parQuantumLine_stats_group_and_compute.yaml
- pipe/parWaterSurface/parWaterSurface_stats_group_and_compute.yaml
- pipe/pressureAir/pressureAir_stats_group_and_compute.yaml
- pipe/relHumidity/relHumidity_stats_group_and_compute.yaml
- pipe/tempAirSingle/tempAirSingle_stats_group_and_compute.yaml
- pipe/tempSoil/tempSoil_stats_group_and_compute.yaml
- pipe/tempSurfacewater/tempSurfacewater_stats_group_and_compute.yaml
Use one image for both averaged and instantaneous
> auto builds for stats_group_and_compute combined module. 

- modules/pub_files/output_files/variables/variables_file.py
Verified output for surfacewater and groundwater pipelines with test image us-central1-docker.pkg.dev/neon-shared-service/neonscience/neon-is-pub-grp-pack:sha-871649a
> remove "_pub" from table name in variables file

- modules_combined/data_source_trino/Dockerfile
- pipe/li192sa/li192sa_cron_daily_and_date_control.yaml
- pipe/li192sa/li192sa_data_source_trino.yaml
- pipe/li192sa/site-list.json
Updated the "neon-avro-genscript" version for the "NSE-10755".
> Nse 10755 li192sa

- .github/workflows/build_push_update_wq.sens.na.yml
- .github/workflows/build_push_wq.sens.na.yml
- .github/workflows/neon-test-auth.yml
- flow/flow.wq.sens.na/Dockerfile
- pipe/waterQuality/waterQuality_qaqc_sensor_na.json
This is PR for flow.wq.sens.ca.  Thanks!
> Choim wq.sens.na

- modules_combined/data_source_trino/Dockerfile
- pipe/gmp343/gmp343_cron_daily_and_date_control.yaml
- pipe/gmp343/gmp343_data_source_trino.yaml
- pipe/gmp343/site-list.json
Please review the changes made for the source type "gmp343".
> Nse 10751 gmp343

- .github/actions/update-pipelines/action.yml
- .github/workflows/DEV_dualfan_site_list.yml
- .github/workflows/DEV_dualfan_update_dag.yml
- .github/workflows/DEV_errored_datums_reader.yml
- .github/workflows/DEV_level1_pipeline_list.yml
- .github/workflows/DEV_li191r_parQuantumLine_update_dag.yml
- .github/workflows/DEV_li191r_site_list.yml
- .github/workflows/DEV_processed_datums_reader.yml
- .github/workflows/DEV_prt_site_list.yml
- .github/workflows/DEV_prt_tempProducts_update_dag.yml
- .github/workflows/DEV_troll_SW_GW_update_dag.yml
- .github/workflows/DEV_troll_site_list.yml
- .github/workflows/DEV_windobserverii_site_list.yml
- .github/workflows/DEV_windobserverii_update_dag.yml
- .github/workflows/neon-test-auth.yml
This is DEV workflows. Thanks!
> Choim dev workflows

- modules/pub_files/database/spatial_units.py
- modules/pub_files/tests/publication_workbook/publication_workbook.py
- modules/pub_files/tests/readme_file/test_readme_file.py
@eahayes9, 
This PR is to fix test failures of 3 missing arguments, dp_number, workbook and table_name after these were added in the source code.
> Choim fix modules error

- flow/tests/testthat/test-wrap-qaqc-plau.R
@eahayes9, 
Commenting one negative test out until the error is figured out. Thanks
> Choim fix flow tests

- modules_combined/data_source_trino/Dockerfile
- pipe/spn1/site-list.json
- pipe/spn1/spn1_cron_daily_and_date_control.yaml
- pipe/spn1/spn1_data_source_trino.yaml
Please review the spn1 pipelines
> Nse 10764 spn1

- modules_combined/data_source_trino/Dockerfile
- pipe/si111/si111_cron_daily_and_date_control.yaml
- pipe/si111/si111_data_source_trino.yaml
- pipe/si111/site-list.json
Cove, please review the changes made for source type "si111", if it looks good please approve and merge the code into master branch
> Nse 10762 si111

- modules_combined/data_source_trino/Dockerfile
- pipe/groundwaterPhysical/groundwaterPhysical_level1_group_consolidate_srf.yaml
- pipe/li840a/li840a_cron_daily_and_date_control.yaml
- pipe/li840a/li840a_data_source_trino.yaml
- pipe/li840a/site-list.json
Please review the pipelines created for source type "li840a"
> Nse 10756 li840a

- modules_combined/data_source_trino/Dockerfile
- pipe/li850/li850_cron_daily_and_date_control.yaml
- pipe/li850/li850_data_source_trino.yaml
- pipe/li850/site-list.json
Cove, created the pipeline for li850 source type. Please review and let me know your comments.
> Nse 10757 li850

- modules_combined/data_source_trino/Dockerfile
- pipe/pump/pump_cron_daily_and_date_control.yaml
- pipe/pump/pump_data_source_trino.yaml
- pipe/pump/site-list.json
Please review the pipeline and let me know your feedback
> added pipelines for pump sourcetype

- pipe/aepg600m/aepg600m_data_source_kafka.yaml
- pipe/cmp22/cmp22_data_source_kafka.yaml
- pipe/dualfan/dualfan_data_source_kafka.yaml
- pipe/g2131i_raw/g2131i_raw_data_source_kafka.yaml
- pipe/hmp155/hmp155_data_source_kafka.yaml
- pipe/l2130i_raw/l2130i_raw_data_source_kafka.yaml
- pipe/li191r/li191r_data_source_kafka.yaml
- pipe/li7200/li7200_data_source_kafka.yaml
- pipe/mcseries/mcseries_data_source_kafka.yaml
- pipe/metone370380/metone370380_event_data_source_kafka.yaml
- pipe/mti300ahrs/mti300ahrs_data_source_kafka.yaml
- pipe/nr01/nr01_data_source_kafka.yaml
- pipe/pluvio_testing/pluvio_data_source_kafka.yaml
- pipe/pqs1/pqs1_data_source_kafka.yaml
- pipe/pressuretransducer/pressuretransducer_data_source_kafka.yaml
- pipe/prt/prt_data_source_kafka.yaml
- pipe/ptb330a/ptb330a_data_source_kafka.yaml
- pipe/sandbox/ONEOFF_level0_bucket_compact.yaml
- pipe/stevenshp/stevenshp_data_source_kafka.yaml
- pipe/troll/troll_data_source_kafka.yaml
- pipe/windobserverii/windobserverii_data_source_kafka.yaml
- pipe/windobserverii_extreme/windobserverii_extreme_data_source_kafka.yaml
Include updating the airflow triggering table in kafka loader pipelines
> Update trigger table

- modules/data_access/tests/test_geojson_converter.py
@eahayes9, 
This is the fix of the test failure of a module.  Can you point to this branch out of master to test it before merging it?  I ran the unit test locally and passed it. Thanks
> fix a module test error

- .github/workflows/build_push_level1_group_consolidate_srf_reshape.yml
> combined module with reshape in level 1

- pipe/tchain/tchain_cron_daily_and_date_control.yaml
- pipe/tempSpecificDepthLakes/tempSpecificDepthLakes_cron_monthly_and_pub_control.yaml
> process another year

- modules/replace_macaddress_with_assetuid/replace_macaddress_with_assetuid.py
- pipe/li7200/li7200_assetuid_macaddress_map.yaml
- pipe/li7200/li7200_cron_daily_and_date_control.yaml
- pipe/li7200/li7200_replace_macaddress_with_assetuid.yaml
Please review the changes made to fix the failing pipeline of "li7200_replace_macaddress_with_assetuid"
> Nse 11377 li7200 macaddress

- flow/tests/testthat/test-wrap-rglr.R
This is the unit test update to fix the error in flow unit tests on Jenkins (eddy4R.base is also upgraded to 0.3.0.)
> added a param ValuFill to the test
